Muser/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
]

mainapp/urls.py
from django.urls import path, include
from mainapp import views

app_name = "mainapp"
urlpatterns = [
	path('', views.index, name='index'),
	path('sign_up/', views.sign_up, name='sign_up'),
	path('log_out/', views.log_out, name='log_out'),
	path('login/', views.login, name='login'),
	path('profile/', views.profile, name='profile'),
	path('library/', views.library, name='library'),
	path('track_page/<int:id>/', views.track_page, name='track_page'),
	path('activate/<uidb64>/<token>', views.activateaccount, name='activate'),
	path('password_request/', views.password_request, name='password_request'),
	path('password_change/<uidb64>/<token>', views.password_change, name='password_change'),
	path('search_page/', views.search_page, name='search_page'),
]

mainapp/models.py
from django.db import models
from django.utils import timezone
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from PIL import Image
from django.conf import settings

# Create your models here.

class Profile(models.Model):
	user = models.OneToOneField(User,on_delete=models.CASCADE)
	tempo = models.FloatField(default=0.0)
	speechiness = models.FloatField(default=0.0)
	energy = models.FloatField(default=0.0)
	profilepic = models.ImageField(default='default.png', upload_to='profile_pic')

	def __str__(self):
		return f'{self.user.username} Profile'

	def save(self, **kwargs):
		super().save()

		pic = Image.open(self.profilepic.path)

		if pic.height > 400 or pic.width > 400:
			output_size = (400, 400)
			pic.thumbnail(output_size)
			pic.save(self.profilepic.path)

class Artist(models.Model):
	artist_name = models.CharField(max_length=128)
	artist_spotify_id = models.CharField(max_length=128)
	artist_uri = models.CharField(max_length=128)

	def __str__ (self):
		return self.artist_name

class Album(models.Model):
	artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
	album_name = models.CharField(max_length=128)
	album_spotify_id = models.CharField(max_length=128)
	album_uri = models.CharField(max_length=128)

	def __str__ (self):
		return self.album_name

class Track(models.Model):
	album = models.ForeignKey(Album, on_delete=models.CASCADE)
	artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
	track_name = models.CharField(max_length=128)
	track_id = models.CharField(max_length=128)
	track_uri = models.CharField(max_length=128)
	track_image = models.CharField(max_length=1024)
	danceability = models.FloatField(default=0.0)
	energy = models.FloatField(default=0.0)
	loudness = models.FloatField(default=0.0)
	speechiness = models.FloatField(default=0.0)
	acousticness = models.FloatField(default=0.0)
	instrumentalness = models.FloatField(default=0.0)
	liveness = models.FloatField(default=0.0)
	valence = models.FloatField(default=0.0)
	tempo = models.FloatField(default=0.0)
	favourites = models.ManyToManyField(User, related_name='favourites', default="none")

	def __str__ (self):
		return self.track_name

class Rating(models.Model):
	track = models.ForeignKey(Track, on_delete=models.CASCADE)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	rating_value = models.IntegerField(default=0)
	description = models.CharField(max_length=2048, default="")
	created_at = models.DateTimeField()

mainapp/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile
class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['profilepic']

mainapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import logout, authenticate, login as auth_login
from django.contrib.sites.shortcuts import get_current_site
from django.conf import settings
import random, spotipy, json, sys, pprint, os, time, numpy as np, pandas as pd
from spotipy.oauth2 import SpotifyClientCredentials
from .models import Artist,Album,Track,Profile,Rating
from django.http import HttpResponse, QueryDict
from datetime import datetime as dt
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import sigmoid_kernel
from datetime import datetime as dt
from django.views.decorators.csrf import csrf_exempt
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text, DjangoUnicodeDecodeError
from .utils import generate_token
from django.core.mail import EmailMessage
from django.conf import settings
from django.contrib import messages

@csrf_exempt
def search_page(request):
	context = {}

	if request.user.is_authenticated and request.method == "PUT":
		user = User.objects.get(id=int(request.user.pk))
		my_favourites = Track.objects.filter(favourites__id=request.user.pk)

		put = QueryDict(request.body)
		objective = put.get('objective')
		track_id = int(put.get('track_id'))
		track = Track.objects.get(id=track_id)

		if objective == "remove_from_favourites" and track in my_favourites:
			print("remove_from_favourites")
			user.favourites.remove(track)
			return HttpResponse(json.dumps({"status_code": 204, "status": "success"}), content_type="application/json")

		if objective == "add_to_favourites" and not track in my_favourites:
			print("add_to_favourites")
			user.favourites.add(track)
			return HttpResponse(json.dumps({"status_code": 204, "status": "success"}), content_type="application/json")

		return HttpResponse(json.dumps({"status_code": 204, "status": "failure"}), content_type="application/json")	

	if request.method == "POST" and 'musicsearch' in request.POST:
		# track_results = []
		query = request.POST['musicsearch']
		client_credentials_manager = SpotifyClientCredentials(client_id=settings.CLIENT_ID, client_secret=settings.CLIENT_SECRET)
		sp = spotipy.Spotify(client_credentials_manager=client_credentials_manager) #spotify object to access API

		result = sp.search(query) #search query
		artist_name = result['tracks']['items'][0]['artists'][0]['name']
		artist_id = result['tracks']['items'][0]['artists'][0]['id']
		artist_uri = result['tracks']['items'][0]['artists'][0]['uri']

		# Adding the artist to the db.
		if Artist.objects.filter(artist_name=artist_name,artist_spotify_id=artist_id,artist_uri=artist_uri).exists():
			the_artist = Artist.objects.get(artist_spotify_id=artist_id,artist_uri=artist_uri)
		else:
			the_artist = Artist.objects.create(artist_name=artist_name,artist_spotify_id=artist_id,artist_uri=artist_uri)

		# Get all of the album that belongs to the searched artist
		sp_albums = sp.artist_albums(artist_uri, limit=1, album_type='album')

		# Adding all the albums associated to the Artist
		for i in range(len(sp_albums['items'])):
			album_name = sp_albums['items'][i]['name']
			album_uri = sp_albums['items'][i]['uri']
			spotify_id = sp_albums['items'][i]['id']
			album_image = sp_albums['items'][i]['id']

			
			if Album.objects.filter(artist=the_artist,album_name=album_name).exists():
				the_album = Album.objects.get(artist=the_artist,album_name=album_name)
			else:
				the_album = Album.objects.create(artist=the_artist,album_name=album_name,album_spotify_id=spotify_id,album_uri=album_uri)

			# Get all the tracks for each album and store it in the db
			tracks = sp.album_tracks(album_uri, limit=12) # pull data on album tracks

			for n in range(len(tracks['items'])): #for each song track
				track_name = tracks['items'][n]['name']
				track_id = tracks['items'][n]['id']
				track_uri = tracks['items'][n]['uri']
				track_image = result['tracks']['items'][0]["album"]["images"][0]["url"]
				features = sp.audio_features(track_uri)#In the future make bulk API request as track_url can be of type list of multiple track uri's.

				danceability = features[0]['danceability']
				energy = features[0]['energy']
				loudness = features[0]['loudness']
				speechiness = features[0]['speechiness']
				acousticness = features[0]['acousticness']
				instrumentalness = features[0]['instrumentalness']
				liveness = features[0]['liveness']
				valence = features[0]['valence']
				tempo = features[0]['tempo']

				if not Track.objects.filter(album=the_album,track_name=track_name).exists():
					the_track = Track.objects.create(album=the_album,artist=the_artist,track_name=track_name,
						track_id=track_id,track_uri=track_uri,track_image=track_image,
						danceability=danceability,energy=energy,loudness=loudness,speechiness=speechiness,
						acousticness=acousticness,instrumentalness=instrumentalness,liveness=liveness,
						valence=valence,tempo=tempo)
		track_results = Track.objects.filter(track_name__icontains=query) | Track.objects.filter(artist__artist_name__icontains=query) | Track.objects.filter(album__album_name__icontains=query)
		track_results = track_results[:10]
		track_results_2 = []
		if request.user.is_authenticated:
			for track in track_results:
				in_favourites = True if track in Track.objects.filter(favourites__id=request.user.pk) else False
				data = {"id": track.id, "track_name": track.track_name, "artist_name": track.artist.artist_name, "in_favourites": in_favourites}
				track_results_2.append(data)
			track_results = track_results_2
			context["track_results"] = track_results
			return render(request,'mainapp/search_page.html',context)
		context["track_results"] = track_results
	return render(request,"mainapp/search_page.html",context)

def sign_up(request):
	# DONE
	if request.method == "POST":
		first_name = request.POST['first_name']
		last_name = request.POST['last_name']
		email = request.POST['email']
		password = request.POST['password']
		password_2 = request.POST['password_2']
		tempo = float(request.POST['tempo'])
		speechiness = float(request.POST['speechiness'])
		energy = float(request.POST['energy'])

		if password and password_2:
			if password != password_2:
				return render(request,'mainapp/sign_up.html',{"message": "Password does not match."})

		if not User.objects.filter(email=email).exists():
			user = User.objects.create_user(username=email, email=email, password=password, first_name=first_name, last_name=last_name)
			user.is_active = False#Change this to false once done
			user.save()
			Profile.objects.create(user=user,tempo=tempo, speechiness=speechiness, energy=energy)
			current_site = get_current_site(request)

			email_subject = "Activate your MuserApp Account"
			message = render_to_string('mainapp/activate.html',
				{"user":user,
				"domain":current_site.domain,
				"uid": urlsafe_base64_encode(force_bytes(user.pk)),
				"token": generate_token.make_token(user)
				})

			email_message = EmailMessage(email_subject, message, settings.EMAIL_HOST_USER, [email])
			email_message.send()

			context = {"activate": "We've sent you an activation link. Please check your email."}
			return render(request,'mainapp/sign_up.html',context)

		else:
			return render(request,'mainapp/sign_up.html',{"message": "E-mail taken already"})

	return render(request,'mainapp/sign_up.html',{})

def login(request):
	# DONE
    if request.method == 'POST' and 'login' in request.POST:
    	print("login")
    	email = request.POST['email']
    	password = request.POST['password']
    	user = authenticate(username=email, password=password)
    	if user:
    		auth_login(request, user)
    		return redirect("mainapp:index")
    	else:
    		return render(request,'mainapp/login.html', {"message": "The username and password does not match, please try again"})
    return render(request,'mainapp/login.html', {})

def password_request(request):
	print("c0")
	if request.method == "POST":
		email = request.POST["email"]
		print("c1")

		try:
			user = User.objects.get(username=email)
		except User.DoesNotExist:
			user = None
		print("c2")

		if user is not None:
			print("c3")
			username = user.first_name

			current_site = get_current_site(request)
			domain = current_site.domain
			print("c4")

			uid = urlsafe_base64_encode(force_bytes(user.pk))
			token = generate_token.make_token(user)
			print("c5q")

			email_subject = "Request to change MuserApp Password"
			message = """Hi {},\n\n
			You have recently request to change your account password.
			Please click this link below to change your account password. \n\n
			http://{}/password_change/{}/{}""".format(username, domain, uid, token)
			print("email sent")

			email_message = EmailMessage(email_subject, message, settings.EMAIL_HOST_USER, [email])
			email_message.send()

		return render(request, "mainapp/password_request.html",{"message": "Check your email for a password change link."})
	return render(request, "mainapp/password_request.html",{})

# def profiles(request):
# 	if not request.user.is_authenticated:
# 		return redirect("mainapp:login")

# 	if request.method == 'POST':
# 		a_form = UserUpdateForm(request.POST, instance=request.user)
# 		f_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

# 		if a_form.is_valid() and  f_form.is_valid():
# 			a_form.save()
# 			f_form.save()
# 			messages.success(request, f'Account Updated')
# 			return redirect('profile')
# 		else:
# 			previous_image = os.path.join(settings.MEDIA_ROOT, request.user.profile.profilepic.name)
# 			a_form = UserUpdateForm(instance=request.user)
# 			f_form = ProfileUpdateForm(instance=request.user.profile)

# 		context = {
# 			'a_form': a_form,
# 			'f_form': f_form
# 		}

mainapp/templates/mainapp/activate.html
{% autoescape on %}

	Hi {{user.username}}
	please click this link below to verify your account

	http://{{domain}}{% url 'mainapp:activate' uidb64=uid token=token %}

{% endautoescape %}

mainapp/templates/mainapp/activate_failed.html
{% extends "mainapp/base.html" %}
{% load staticfiles %}
{% block content %}
<div class="container">
	<h2>Something went wrong, please re-request the link.</h2>
</div><br><br>
{% endblock %}

mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html>
   <head>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      <!-- <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}"/> -->
      <!-- <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}"/> -->
      <!-- <link rel="stylesheet" type="text/css" href="{% static 'css/track.css' %}"/> -->
      <title>MuserApp</title>
   </head>
   <body>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
         <div class="container">
            <a class="navbar-brand" href="{% url 'mainapp:index' %}">MuseR</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
               <ul class="navbar-nav ml-auto">
                  <li class="nav-item active">
                     <a class="nav-link" href="{% url 'mainapp:index' %}">Home
                        <span class="sr-only">(current)</span>
                     </a>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link" href="{% url 'mainapp:search_page' %}">Search</a>
                  </li>
                  {% if user.is_authenticated %}
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'mainapp:profile' %}">Profile</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'mainapp:library' %}">My Library</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'mainapp:log_out' %}">Logout</a>
                     </li>
                  {% else %}
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'mainapp:login' %}">Login</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'mainapp:sign_up' %}">Signup</a>
                     </li>
                  {% endif %}
               </ul>
            </div>
         </div>
      </nav>
      <br><br><br><br>
      {% block content %}
      {% endblock %}
      <footer class="footer py-4 bg-dark text-white-50 fixed-bottom" style="flex-shrink: none;">
      <div class="container text-center">
         <small style="color: white;">Copyright &copy; MuseR</small>
      </div>
   </footer>
      <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
   </body>
</html>

mainapp/templates/mainapp/index.html
{% extends "mainapp/base.html" %}
{% load static %}
{% block content %}
<style type="text/css">
	body {
		background: url({% static 'images/img.png' %}) no-repeat center center fixed;
		-webkit-background-size: cover;
		-moz-background-size: cover;
		background-size: cover;
		-o-background-size: cover;
		min-height:100vh;
	}
	.bg-text {
		background-color: rgb(0,0,0);
		background-color: rgba(0,0,0, 0.65);
		color: white;
		font-weight: 400;
		position: absolute;
		top: 70%;
		left: 50%;
		transform: translate(-50%, -50%);
		z-index: 2;
		width: 50%;
		padding: 20px;
		text-align: center;
	}
	footer {
		position: absolute;
		left: 0;
		right: 0;
		bottom: 0;
		background-color: #4C4;
		height: 30px;
	}
</style>
<div class="container">
	<div>
		<img src="{% static 'images/logo.png' %}" class="img-fluid rounded mx-auto d-block" alt="Responsive image" alt="" style="width:200px;margin-top: -31px;">
	</div><br><br>
	<div>
		<div class="bg-text">
			<h1>Welcome to MuseR</h1>
			<p>We provide you with the best music recommendations for the dicovery of new music</p>
			{% if not user.is_authenticated %}
			<p>Signup now and start getting personalized music recommendations</p>
				<a href="{% url 'mainapp:sign_up' %}" class="btn btn-primary btn-lg">Sign Up</a>
			{% endif %}
		</div>
	</div>
	<br><br><br><br>
</div>
	
{% endblock content %}

mainapp/templates/mainapp/library.html
{% extends "mainapp/base.html" %}
{% load static %}
{% block content %}
<section id="tabs">
	<div class="container">
		<h2>My Library</h2>
		<div class="row">
			<div class="col-xs-12 ">
				<nav>
					<div class="nav nav-tabs nav-fill" id="nav-tab" role="tablist">
						<a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">My Favourites</a>
						<a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">My Recommendations</a>
					</div>
				</nav>
				<div class="tab-content py-3 px-3 px-sm-0" id="nav-tabContent">
					<div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab" style="height:500px;overflow:auto;">
						{% if my_favourites %}
							<table class="table" id="favourites-table" style="table-layout:fixed;">
								<thead class="thead-dark">
									<tr>
										<th scope="col">Title</th>
										<th scope="col">Artist</th>
										<th scope="col">Action</th>
									</tr>
								</thead>
								<tbody>
									{% for tracks in my_favourites %}
										<tr id="my_favourites.{{tracks.id}}">
											<th><a href="{% url 'mainapp:track_page' id=tracks.id %}">{{tracks.track_name}}</a></th>
											<td>{{tracks.artist.artist_name}}</td>
											<td>
												<button type="submit" class="btn btn-danger" id="remove_from_favourites" onclick="remove_from_favourites('{{tracks.id}}');">Remove from my Favourites</button>
											</td>
										</tr>
									{% endfor %}
								</tbody>
							</table>
						{% else %}
							<table class="table" id="favourites-table" style="table-layout:fixed;">
								<thead class="thead-dark">
									<tr>
										<th scope="col">Title</th>
										<th scope="col">Artist</th>
										<th scope="col">Action</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td><p>None found</p></td>
									</tr>
								</tbody>
							</table><br><br><br><br><br><br><br><br><br><br>
						{% endif %}
					</div>
					<div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab" style="height:500px;overflow:auto;">
						{% if my_recommendation %}
							<table class="table" id="recommendation-table" style="table-layout:fixed;">
								<thead class="thead-dark">
									<tr>
										<th scope="col">Title</th>
										<th scope="col">Artist</th>
									</tr>
								</thead>
								<tbody>
									{% for tracks in my_recommendation %}
										<tr id="{{tracks.id}}">
											<th><a href="{% url 'mainapp:track_page' id=tracks.id %}">{{tracks.track_name}}</a></th>
											<td>{{tracks.artist.artist_name}}</td>
										</tr>
									{% endfor %}
								</tbody>
							</table>
						{% else %}
							<table class="table" id="recommendation-table" style="table-layout:fixed;">
								<thead class="thead-dark">
									<tr>
										<th scope="col">Title</th>
										<th scope="col">Artist</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td><p>None found</p></td>
									</tr>
								</tbody>
							</table>
							<br><br><br><br><br><br><br><br><br><br>
						{% endif %}
					</div>
				</div>
			</div>
		</div>
	</div>
</section><br><br>
<script type="text/javascript">
	function remove_from_favourites(track_id){
		$.ajax({
			type: "PUT",
			data: {
				objective: 'remove_from_favourites',
				track_id: track_id,
				csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
			},
			success: function(response) {
				if(response.status_code==204 && response.status=="success"){
					var row = document.getElementById("my_favourites."+track_id);
					var table = row.parentNode;
					while ( table && table.tagName != 'TABLE' )
					table = table.parentNode;
					if ( !table )
						return;
					table.deleteRow(row.rowIndex);
				}
			}
		})
	}
</script>
{% endblock %}

mainapp/templates/mainapp/login.html
{% extends "mainapp/base.html" %}
<!-- {% load crispy_forms_tags %} -->
{% load static %}
{% block content %}
<style type="text/css">
	body{
		background: url({% static 'images/6.jpg' %}) no-repeat center;
		margin: 0; height: 100%; overflow: hidden;
	}
</style>
	<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
	<div class = "container">
		<div class="d-flex justify-content-center">
			<form method="post" name="Login_Form" class="form">
				{% csrf_token %}
				<h2>Login</h2>
				{% if message %}
					<div class="alert alert-danger" role="alert">
						{{message}}
					</div>
				{% endif %}
				<input type="text" name="login" hidden></input>
				<div class="input-group">
					<input type="text" name="email" id="email" required>
					<label for="email">Email</label>
				</div>
				<div class="input-group">
					<input type="password" name="password" id="password" required>
					<label for="password">Password</label>
				</div>
				<input type="submit" value="Login" class="submit-btn">
				<a href="{% url 'mainapp:password_request' %}" class="forgot-pw">Forgot Password?</a>
			</form>
		</div>
	</div><br><br>
{% endblock content %}

mainapp/templates/mainapp/password_request.html
{% extends "mainapp/base.html" %}
{% load staticfiles %}
{% block content %}
<style type="text/css">
    body{
        background: url({% static 'images/6.jpg' %}) no-repeat center;
        margin: 0; height: 100%; overflow: hidden;
    }
</style>
    <link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
    <div class="container" style="margin-left: 450px;">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="text-center">
                            <div class="panel-body">
                                <form method="post" class="form">
                                    {% csrf_token %}
                                    {% if message %}
                                        <div style="color: black; text-align: center;" class="alert alert-success" role="alert">{{message}}</div>
                                    {% endif %}
                                    <a href="#" class="close">&times;</a>
                                    <h2>Reset Password</h2>
                                    <div class="input-group">
                                        <input type="email" name="email" id="email" required>
                                        <label for="email">Email</label>
                                    </div>
                                    <input type="submit" value="Submit" class="submit-btn">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div><br><br>
{% endblock %}

mainapp/templates/mainapp/search_page.html
{% extends "mainapp/base.html" %}
{% load static %}
{% block content %}
	<div class="container">
		<form class="form-horizontal" role="form" method="post">
			{% csrf_token %}
			<div class="input-group mb-3">
				<input type="text" class="form-control" name="musicsearch" placeholder="Search" aria-label="Search" aria-describedby="basic-addon2">
				<div class="input-group-append">
					<button class="btn btn-outline-secondary" type="submit">Search</button>
				</div>
			</div>
		</form>
	</div>
	<div class="container" style="margin-bottom: 50px;">
		{% if track_results %}
			<table class="table">
				<thead class="thead-dark">
					<tr>
					</tr>
				</thead>
				{% for tracks in track_results %}
					<tbody>
						<tr id="track.{{tracks.id}}">
							<th><a href="{% url 'mainapp:track_page' id=tracks.id %}">{{tracks.track_name}}</a></th>
							{% if user.is_authenticated %}
								<th>by {{tracks.artist_name}}</th>
							{% else %}
								<th>by {{tracks.artist.artist_name}}</th>
							{% endif %}
							
							{% if user.is_authenticated %}
								{% if tracks.in_favourites %}
									<th><button type="button" class="btn btn-danger" onclick="remove_from_favourites('{{tracks.id}}');">Remove from my Library</button></th>
								{% else %}
									<th><button type="button" class="btn btn-success" onclick="add_to_favourites('{{tracks.id}}');">Add to My Library</button></th>
								{% endif %}
								
							{% endif %}
						</tr>
					</tbody>
				{% endfor %}
			</table>
		{% endif %}
	</div><br><br>
<script type="text/javascript">
	function remove_from_favourites(track_id){
		track_id = track_id.toString();
		$.ajax({
            type: "PUT",
            data: {
                objective: 'remove_from_favourites',
                track_id: track_id,
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
            },
            success: function(response) {
            	console.log(response);
            	if(response.status_code==204 && response.status=="success"){
            		var row = document.getElementById("track."+track_id).cells[2];
            		row.innerHTML = '<button type="button" class="btn btn-success" onclick="add_to_favourites('+track_id+');">Add to My Library</button>';
            		console.log("done removed");
            	}
            }
        })
	}

	function add_to_favourites(track_id){
		track_id = track_id.toString();
		$.ajax({
            type: "PUT",
            data: {
                objective: 'add_to_favourites',
                track_id: track_id,
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
            },
            success: function(response) {
            	console.log(response);
            	if(response.status_code==204 && response.status=="success"){
            		track_id = parseInt(track_id);
            		var row = document.getElementById("track."+track_id).cells[2];
            		row.innerHTML = '<button type="button" class="btn btn-danger" onclick="remove_from_favourites('+track_id+');">Remove from my Library</button>';
            	}
            }
        })
	}
</script>
{% endblock content %}